# Generated by Django 4.2.24 on 2025-10-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indices_stock', models.CharField(choices=[('NIFTY', 'Nifty 50'), ('BANKNIFTY', 'Bank Nifty'), ('STOCK', 'Stock')], max_length=50)),
                ('bias', models.CharField(choices=[('BULLISH', 'Bullish'), ('BEARISH', 'Bearish'), ('NEUTRAL', 'Neutral')], max_length=20)),
                ('setup', models.CharField(max_length=100)),
                ('strategy', models.CharField(max_length=100)),
                ('days_to_expiry', models.CharField(max_length=50)),
                ('main_lots', models.PositiveIntegerField()),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hedge_lots', models.PositiveIntegerField(blank=True, null=True)),
                ('price_per_hedge_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_profit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_loss', models.DecimalField(decimal_places=2, max_digits=12)),
                ('capital', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
