# Generated by Django 4.2.24 on 2025-10-04 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='trade',
            name='bias',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='trade',
            name='indices_stock',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Strike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strike_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('option_type', models.CharField(choices=[('CE', 'Call'), ('PE', 'Put')], max_length=2)),
                ('position', models.CharField(choices=[('B', 'Buy'), ('S', 'Sell')], max_length=4)),
                ('lots', models.PositiveIntegerField(default=1)),
                ('expiry_date', models.DateField()),
                ('ltp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strikes', to='trades.trade')),
            ],
        ),
    ]
